# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "deal-ai"
client_id = "65c4954be22a7ade750f78894f334d0f"
application_url = "https://thread-gods-lift-breach.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://thread-gods-lift-breach.trycloudflare.com/auth/callback",
  "https://thread-gods-lift-breach.trycloudflare.com/auth/shopify/callback",
  "https://thread-gods-lift-breach.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-de06169f.myshopify.com"
