# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "deal-ai"
client_id = "bc90959d38caf086c5dabfe21dc483c5"
application_url = "https://appear-remove-reading-center.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://appear-remove-reading-center.trycloudflare.com/auth/callback",
  "https://appear-remove-reading-center.trycloudflare.com/auth/shopify/callback",
  "https://appear-remove-reading-center.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-de06169f.myshopify.com"
