# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "deal-ai"
client_id = "d6f1f127c09bd28af9939ff2073e6e34"
application_url = "https://hood-comparisons-successfully-enemy.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://hood-comparisons-successfully-enemy.trycloudflare.com/auth/callback",
  "https://hood-comparisons-successfully-enemy.trycloudflare.com/auth/shopify/callback",
  "https://hood-comparisons-successfully-enemy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-de06169f.myshopify.com"
